# Generated by Django 5.2.1 on 2025-05-15 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0003_pet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.TextField(default='Not provided'),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
