# Generated by Django 5.2.1 on 2025-05-15 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0004_remove_profile_email_profile_address_profile_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adoptionapplication',
            name='alt_email',
        ),
        migrations.RemoveField(
            model_name='adoptionapplication',
            name='alt_first_name',
        ),
        migrations.RemoveField(
            model_name='adoptionapplication',
            name='alt_last_name',
        ),
        migrations.RemoveField(
            model_name='adoptionapplication',
            name='alt_phone',
        ),
        migrations.RemoveField(
            model_name='adoptionapplication',
            name='alt_relationship',
        ),
        migrations.RemoveField(
            model_name='adoptionapplication',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='adoptionapplication',
            name='family_explanation',
        ),
        migrations.RemoveField(
            model_name='adoptionapplication',
            name='family_support',
        ),
        migrations.RemoveField(
            model_name='adoptionapplication',
            name='has_adopted_before',
        ),
        migrations.RemoveField(
            model_name='adoptionapplication',
            name='occupation',
        ),
        migrations.RemoveField(
            model_name='adoptionapplication',
            name='pet_alone_hours',
        ),
        migrations.RemoveField(
            model_name='adoptionapplication',
            name='pet_care_backup',
        ),
        migrations.RemoveField(
            model_name='adoptionapplication',
            name='plan_for_moving',
        ),
        migrations.AlterField(
            model_name='adoptionapplication',
            name='pronouns',
            field=models.CharField(choices=[('She/her', 'She/her'), ('He/him', 'He/him')], max_length=10),
        ),
    ]
