# Generated by Django 5.2.1 on 2025-05-18 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0005_remove_adoptionapplication_alt_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='sex',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='pet',
            name='weight',
            field=models.FloatField(default=0.0),
        ),
    ]
