# Generated by Django 5.2.1 on 2025-05-18 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0006_pet_sex_pet_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='weight_unit',
            field=models.CharField(choices=[('kg', 'Kilograms'), ('lb', 'Pounds')], default='kg', max_length=2),
        ),
    ]
