# Generated by Django 5.2.1 on 2025-05-26 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0007_pet_weight_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adoptionapplication',
            name='pet_description',
        ),
        migrations.AddField(
            model_name='adoptionapplication',
            name='pet_to_adopt',
            field=models.CharField(default='Not specified', max_length=100),
        ),
    ]
