# Generated by Django 5.2.1 on 2025-05-26 12:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0008_remove_adoptionapplication_pet_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cause', models.CharField(choices=[('Neutering', 'Neutering'), ('Shelter', 'Shelter'), ('Food', 'Food'), ('General', 'General')], max_length=50)),
                ('receipt', models.FileField(blank=True, upload_to='donation_receipts/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'pdf'])])),
            ],
        ),
    ]
