# Generated by Django 5.2.1 on 2025-05-26 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0009_donation'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='qr_image',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
