# Generated by Django 5.2.1 on 2025-05-26 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0010_donation_qr_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='qr_image',
        ),
    ]
