# Generated by Django 5.2.1 on 2025-05-26 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0011_remove_donation_qr_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptionapplication',
            name='pet_to_adopt',
            field=models.CharField(choices=[('Tiger', 'Tiger'), ('Tiny Terror', 'Tiny Terror'), ('Pinpin', 'Pinpin')], default='Tiger', max_length=100),
        ),
    ]
